name: Java CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    name: Build Docker Container and Deploy to Kubernetes
    steps:
      - uses: actions/checkout@v2
      - name: Download Maven build artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact.jar
          path: github-actions-java-maven/target
      - name: Build Docker container
        working-directory: github-actions-java-maven
        run: |
          docker build -t de.rieckpil.blog/github-actions-sample .
      - name: Access secrets
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run: echo "Content of secret - $SUPER_SECRET"
      - name: Push Docker images
        run: echo "Pushing Docker image to Container Registry (e.g. ECR)"
      - name: Deploy application
        run: echo "Deploying application (e.g. Kubernetes)"